name: Pop!_OS CI

on:
  push:
    branches: [ add-pop-os ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install shellcheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck
      - name: Shellcheck create_image.sh
        run: |
          if [ -f create_image.sh ]; then
            shellcheck -x create_image.sh || true
          else
            echo "create_image.sh not found, skipping shellcheck"
          fi
      - name: Check README mentions Pop!_OS
        run: grep -qi "Pop!_OS" README.md

  download-popos:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - name: Download Pop!_OS image
        run: |
          set -euo pipefail
          POP_URL="https://iso.pop-os.org/22.04/arm64/raspi/4/pop-os_22.04_arm64_raspi_4.img.xz"
          echo "Downloading $POP_URL"
          wget -c "$POP_URL" -O pop-os.img.xz
          echo "Downloaded: $(stat -c%s pop-os.img.xz) bytes"
          echo "Testing xz archive"
          unxz -t pop-os.img.xz
      - name: Extract first 1MiB (sanity)
        run: |
          xzcat pop-os.img.xz | head -c 1048576 > head1MiB.bin
          file head1MiB.bin
